// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock_store

import (
	store "github.com/StuartsHome/YA-KVS/store"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Store) Get() (store.Response, error) {
	ret := _m.Called()

	var r0 store.Response
	if rf, ok := ret.Get(0).(func() store.Response); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(store.Response)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
